---
apiVersion: v1
kind: Pod
metadata:
  name: diagnostics
  namespace: default
spec:
  #  nodeSelector:
  #  kubernetes.io/hostname: ${HOSTNAME}
  hostNetwork: true
  volumes:
    - hostPath:
        path: /var/run/docker.sock
      name: dockersocket
    - hostPath:
        path: /proc
      name: procdir
    - hostPath:
        path: /sys/fs/cgroup
      name: cgroups
    - hostPath:
        path: /var/log
      name: logs
  containers:
  - name: diagnostics
    image: faraazkhan/diagnostics
    imagePullPolicy: Always
    securityContext:
      privileged: true
    volumeMounts:
      - name: dockersocket
        mountPath: /var/run/docker.sock
      - name: procdir
        mountPath: /host/proc
        readOnly: true
      - name: cgroups
        mountPath: /host/sys/fs/cgroup
        readOnly: true
      - name: logs
        mountPath: /host/var/log
        readOnly: true
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
