---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: diagnostics
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: diagnostics
    spec:
      nodeSelector:
        kubernetes.io/hostname: ${HOSTNAME}
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        - hostPath:
						path: /var/log
					name: logs
      containers:
      - name: diagnostics
        image: faraazkhan/diagnostics
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        terminationGracePeriodSeconds: 30
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
					- name: logs
						mountPath: /host/var/log
            readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 200Mi

